version: "3.7"
services:
  zp_app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: zp_app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - kas
    environment:
      TZ: "Asia/Almaty"

  zp_postgres:
    image: postgres:latest
    container_name: zp_postgres
    restart: always
    env_file: ./.env
    ports:
      - 5432:5432
    networks:
      - kas
    environment:
      TZ: "Asia/Almaty"

  zp_nginx:
    image: nginx:alpine
    container_name: zp_nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - kas
    environment:
      TZ: "Asia/Almaty"
networks:
  kas:
    driver: bridge